export const ROUTES = {
  home: "/",
  products: "/products",
  productDetail: (slug: string) => `/products/${slug}`,
  category: (slug: string) => `/categories/${slug}`,
  categories: "/categories",
  cart: "/cart",
  checkout: "/checkout",
  orders: "/orders",
  orderDetail: (id: string) => `/orders/${id}`,
  wishlist: "/wishlist",
  profile: "/profile",
  login: "/auth/login",
  register: "/auth/register",
  forgotPassword: "/auth/forgot-password",
  resetPassword: (token: string) => `/auth/reset-password/${token}`,
  about: "/about",
  contact: "/contact",
  offers: "/offers",
  wallpaper: "/categories/wallpaper",
  floorItem: "/categories/floor-item",
  blind: "/categories/blind",
  glassPaper: "/categories/glass-paper",
  wallPanel: "/categories/wall-panel",
  kitchenItem: "/categories/kitchen-item",
  admin: {
    dashboard: "/admin",
    products: "/admin/products",
    orders: "/admin/orders",
    customers: "/admin/customers",
    categories: "/admin/categories",
  },
} as const;
